# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'IntellectDress' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for IntellectDress
   pod 'AFNetworking', '~> 3.1.0'
   pod 'SDWebImage','~>3.7.6'
   pod 'Masonry','~>1.0.1'
   pod 'MJRefresh','~>3.1.0'
   pod 'PNChart','~>0.8.8'
   pod ’SVProgressHUD’,’~>2.0.3’
   pod 'FMDB','~>2.6.2'
   pod 'MBProgressHUD','~>0.9.2'
   pod 'SDCycleScrollView','~>1.65'
   pod 'MOBFoundation','~>1.5.3'
   pod 'IQKeyboardManager'
   pod 'YCXMenu'
   

  target 'IntellectDressTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IntellectDressUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
